"""Compatibility facade for anchor-projection planning helpers."""

from .planning_anchor_evaluation import (
    _projected_anchor_candidate_evaluation,
    _same_action_anchor_projection_candidate_evaluation,
    evaluate_candidate_paths,
)
from .planning_anchor_grid import (
    _best_reachable_anchor_in_component,
    _bool_grid,
    _cell_distance_m_or_none,
    _cell_list,
    _cell_manhattan_or_none,
    _component_id_at,
    _component_size,
    _connected_component_labels,
    _grid_distance_map,
    _grid_path,
    _grid_value,
    _inflated_passable_mask,
    _mask_neighbors,
    _mask_value,
    _nearest_inflated_passable_anchor,
    _path_cost_for_payload,
)
from .planning_anchor_projection import (
    _anchor_projection_analysis,
    _anchor_projection_candidate_generation_payload,
    _anchor_projection_reject_reason,
    _planner_validated_distance_exception_safe,
    _proxy_anchor_route_comparison,
    _proxy_route_unavailable,
    _trainability_distance_reject_reasons,
    anchor_projection_candidate_config_from_mapping,
)


__all__ = (
    "evaluate_candidate_paths",
    "_same_action_anchor_projection_candidate_evaluation",
    "_projected_anchor_candidate_evaluation",
    "anchor_projection_candidate_config_from_mapping",
    "_anchor_projection_candidate_generation_payload",
    "_trainability_distance_reject_reasons",
    "_planner_validated_distance_exception_safe",
    "_anchor_projection_analysis",
    "_anchor_projection_reject_reason",
    "_proxy_anchor_route_comparison",
    "_proxy_route_unavailable",
    "_connected_component_labels",
    "_best_reachable_anchor_in_component",
    "_grid_distance_map",
    "_component_id_at",
    "_component_size",
    "_cell_list",
    "_cell_manhattan_or_none",
    "_cell_distance_m_or_none",
    "_inflated_passable_mask",
    "_nearest_inflated_passable_anchor",
    "_grid_path",
    "_mask_neighbors",
    "_path_cost_for_payload",
    "_bool_grid",
    "_mask_value",
    "_grid_value",
)
